version: '3'

volumes:
  content_db:
  static:

services:
  service:
    build: app
    expose:
      - "8000"
    env_file:
      - ./.env
    volumes:
      - static:/var/www/static
    depends_on:
      - theatre-db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/data/static
    depends_on:
      - service
    ports:
      - "80:80"

  theatre-db:
    image: postgres:14
    restart: always
    volumes:
      - content_db:/var/lib/postgresql/data/
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - ./.env
